name: 'Testing Var And Secret Access'
on:
  pull_request:
    branches: 
      - main

jobs:
  access-var-in-calling-repo:
    name: Accessing In Calling Repo
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'ls -al'
        run: ls -al
      - name: 'Output REPO_VAR_1'
        run: echo ${{vars.REPO_VAR_1}}
      - name: 'Output REPO_SECRET_1'
        run: echo ${{vars.REPO_SECRET_1}}
      - name: 'Output REPO_VAR_2'
        run: echo ${{vars.REPO_VAR_2}}
